### PR TITLE
Upgrade included rope libs to latest releases

### PR DESCRIPTION
**Pull request by TFenby**
rope: 0.10.2
rope_py3k: 0.9.4-1

-----

Likely solves #509, and they're just old at this point anyway.

### CODE REVIEW

**Comment by Telling** [comment]
This pull request solves https://github.com/python-rope/ropevim/issues/39 which is quite a big one.

**Comment by feoh** [comment]
+1 this is a totally debilitating problem on Yosemite.  I've had to turn rope off for now but IMO that's one of the creature comforts I love in python-mode.

**Comment by amir-hadzic** [comment]
Just a note that it doesn't solve #509 for me. I'm on Arch Linux, Vim 7.4.663.

**Comment by K-Guan** [comment]
I've try this, but when I type a full stop I got this message: 
`[Pymode] Init Rope project: $HOME`

And then Vim was no response, so I have to kill the process.

I'm on Arch Linux (x64), Vim 7.4.778-1
@ccope Any ideas?

**Comment by klen** [comment]
Thank you!

**Comment by K-Guan** [comment]
Oh, I forgot this: My vim is `vim-python3`, so my vim was compiled with python3.

**Pull request merged**
